# change this also in new_poll.js
DAY_INCREMENT_DEFAULT = 1
TIME_INCREMENT_DEFAULT = 60


UNKNOWN = "❔"
AVAILABLE = "✅"
UNAVAILABLE = "❌"
NOT_PREFERED = "✔️"

AVAILABILITY = [UNKNOWN, AVAILABLE, UNAVAILABLE, NOT_PREFERED]
DEFAULT_AVAILABILITY = UNKNOWN